### ISSUE TITLE
Not implemented error when creating VM

### ISSUE THREAD

**Issue by alexwaibel** [hashicorp/packer-plugin-proxmox#146] opened 2023-01-25 07:45 UTC
#### Overview of the Issue

I was previously using the built in proxmox builder and am attempting to migrate to the latest release from this repo. I was able to init packer fine with the new required_plugins config but when I try to run the build it fails on the "Creating VM" step with a not implemented error. I don't see this error when using the builtin "proxmox" builder, only when I switch to using "proxmox-iso", but I need to switch to take advantage of the new efi_config options.

#### Reproduction Steps

I have a public repo with my packer files [here](https://github.com/alexwaibel/home-ops/blob/main/packer/images/debian.pkr.hcl). 

### Plugin and Packer version

Packer v1.8.5
Proxmox plugin v 1.1.1
Proxmox VE 7.3-4

### Simplified Packer Buildfile

[Gist with simplified buildfile.](https://gist.github.com/alexwaibel/accea6bda9a2961277294eff5748b119)

### Operating system and Environment details

Running packer in ubuntu 20.04.4 in wsl2

### Log Fragments and crash.log files

[Gist with logs](https://gist.github.com/alexwaibel/ceda979e7ad812f65ee934abeafc6b02)

**Comment by sebastian-de** [comment] 2023-01-25 08:55
Please note that there are still issues with the new `efi_config` parameter: #145 

Regarding your issue: Can you try running your configuration with an already present `iso_file` instead of `iso_url`?
Uploading ISOs via the Proxmox API has always been problematic for me.

**Comment by zarichard** [comment] 2023-01-25 19:27
I ran into the same issue using additional_iso_files with cd_files. Removing the additional_iso_files made it work (using iso_file option for the os iso so no other copying), or downgrading the plugin to 1.1.0 without any other changes also fixed it (ie, still using the additional_iso_files).

So to me it looks like something that was introduced in the latest release of the plugin.

**Comment by alexwaibel** [comment] 2023-01-25 23:19
Thanks for the heads up about `efi_config` and the speedy response @sebastian-de. Switching to `iso_file` did resolve the error. I also tried downgrading to v1.1.0 per @zarichard suggestion and this also got past the error so I agree, seems to be a regression with iso handling introduced in the most recent release.

**Comment by sebastian-de** [comment] 2023-01-26 06:14
Since the code for file upload didn't change since the last version of this plugin, this issue has to be related to updating `proxmox-api-go`. I suspect this is because of the introduction of [HTTP headers](https://github.com/Telmate/proxmox-api-go/pull/202).

**Comment by sebastian-de** [comment] 2023-01-27 11:44
Wasn't easy to find the root cause of this, but it indeed was because of wrong HTTP headers.
I created a PR for `proxmox-api-go`: https://github.com/Telmate/proxmox-api-go/pull/232
Once it's merged, I'll open a PR here to get the API updated.

**Closed** 2023-02-01 14:47 UTC
Labels: bug
