### ISSUE TITLE
Build fails to unmount iso when finished

### ISSUE THREAD

**Issue by Quiphius** [hashicorp/packer-plugin-proxmox#83] opened 2022-05-03 18:04 UTC
#### Overview of the Issue

When build new debian 11 template the build finishes with an error:
==> proxmox-iso.base: Cannot eject ISO from cdrom drive, ide2 is not present, or not a cdrom media

Build finishes and it is possible to unmound cdrom.

When looking in the pve gui it seems the string for the cdrom has changed and I would guess the problem is
in the file step_finalize_iso.go line 41, the function call HasSuffix has to probably be changed to Contains.

#### Reproduction Steps

Any build against a fully patched proxmox server

### Plugin and Packer version

Packer v1.8.0

### Simplified Packer Buildfile

any build against a fully patched proxmox will probably fail

### Operating system and Environment details

Build: ubuntu 20.04
Poxmox: Virtual Environment 7.1-12

### Log Fragments and crash.log files

2022/05/03 17:58:30 [INFO] (telemetry) ending ansible
2022/05/03 17:58:30 packer-provisioner-ansible plugin: shutting down the SSH proxy
==> proxmox-iso.base: Stopping VM
==> proxmox-iso.base: Converting VM to template
2022/05/03 17:58:32 packer-builder-proxmox-iso plugin: template_id: 10600
==> proxmox-iso.base: Cannot eject ISO from cdrom drive, ide2 is not present, or not a cdrom media
==> proxmox-iso.base: Provisioning step had errors: Running the cleanup provisioner, if present...
Build 'proxmox-iso.base' errored after 5 minutes 47 seconds: Cannot eject ISO from cdrom drive, ide2 is not present, or not a cdrom media

2022/05/03 17:58:37 [INFO] (telemetry) ending proxmox-iso.base
==> Wait completed after 5 minutes 47 seconds
2022/05/03 17:58:37 machine readable: error-count []string{"1"}
==> Some builds didn't complete successfully and had errors:
2022/05/03 17:58:37 machine readable: proxmox-iso.base,error []string{"Cannot eject ISO from cdrom drive, ide2 is not present, or not a cdrom media"}
==> Builds finished but no artifacts were created.
==> Wait completed after 5 minutes 47 seconds
2022/05/03 17:58:37 [INFO] (telemetry) Finalizing.

==> Some builds didn't complete successfully and had errors:
--> proxmox-iso.base: Cannot eject ISO from cdrom drive, ide2 is not present, or not a cdrom media

==> Builds finished but no artifacts were created.
2022/05/03 17:58:38 waiting for all plugin processes to complete...
2022/05/03 17:58:38 /usr/bin/packer: plugin process exited
2022/05/03 17:58:38 /usr/bin/packer: plugin process exited

**Comment by goffinf** [comment] 2022-05-05 15:45
**Proxmox version**: **7.1-12**
**ISO used for Packer build**: **ubuntu-20.04.1-live-server-amd64** / **ubuntu-20.04.3-live-server-amd64**

Also seeing this behaviour ... here is the end of the packer log. Although the prompt to clean/abort/retry appears, the template is still created, but retains the CDROM drive (ide2) used to mount the ISO as well as a CloudInit drive as ide0.

```
...
2022/05/05 15:22:40 ui: ==> proxmox-iso.ubuntu-base-os-template: Stopping VM
2022/05/05 15:22:42 ui: ==> proxmox-iso.ubuntu-base-os-template: Converting VM to template
2022/05/05 15:22:42 packer-builder-proxmox-iso plugin: template_id: 9100
2022/05/05 15:22:42 ui: ==> proxmox-iso.ubuntu-base-os-template: Adding a cloud-init cdrom in storage pool local-lvm
2022/05/05 15:22:46 ui error: ==> proxmox-iso.ubuntu-base-os-template: Cannot eject ISO from cdrom drive, ide2 is not present, or not a cdrom media
2022/05/05 15:22:46 ui error: ==> proxmox-iso.ubuntu-base-os-template: Cannot eject ISO from cdrom drive, ide2 is not present, or not a cdrom media
2022/05/05 15:22:46 ui: ==> proxmox-iso.ubuntu-base-os-template: Step "stepFinalizeISOTemplate" failed
2022/05/05 15:22:46 ui: ask: ==> proxmox-iso.ubuntu-base-os-template: [c] Clean up and exit, [a] abort without cleanup, or [r] retry step (build may fail even if retry succeeds)?
...
```
A consequence of not unmounting the CDROM is that CloudInit is assigned ide0 (the code takes the next available number starting from 0 - [see](https://github.com/hashicorp/packer-plugin-proxmox/blob/a7d21d2626f789774e720d8800b32e5a49d3d890/builder/proxmox/common/step_finalize_template_config.go#L58). However, if you then try and create a new template based on this one (using the [proxmox-clone](https://www.packer.io/plugins/builders/proxmox/clone) builder, it will fail connect over the SSH communicator since (I believe) that it is expecting the CloudInit drive to be ide0. I have confirmed that behaviour by removing the CDROM drive and CloudInit drive from the base image (template) and adding a new CloudInit back with ide2, then the connection is successful and the build and provision steps (including cloud-init) run as expected.

Yes, to avoid the Packer build error, you can set unmount_iso to **false** and remove afterwards, but that still leaves the CloudInit drive assigned to ide0 which for some reason appears to bring more problematic behaviour (unless there is a way of telling Packer the CloudInit device ??)

**Comment by n8rade** [comment] 2022-05-25 00:46
I see that there's a Pull Request for this, but I don't know when it may make it through so I made a workaround for this for the time being by adding a post-processor:

```
post-processor "shell-local" {
  command = "curl -k -X POST -H 'Authorization: PVEAPIToken=${var.proxmox_username}=${var.proxmox_token}' --data-urlencode delete=ide2 ${var.proxmox_api}/nodes/${var.proxmox_node}/qemu/${var.rhel8_id}/config"
}
```

I grabbed this from the Proxmox API Docs: https://pve.proxmox.com/pve-docs/api-viewer/index.html#/nodes/{node}/qemu/{vmid}/config

Hope this helps!

**Closed** 2022-05-25 14:40 UTC
Labels: bug
