### ISSUE TITLE
Do not upload an existing iso_url

### ISSUE THREAD

**Issue by rgl** [hashicorp/packer-plugin-proxmox#79] opened 2022-04-08 07:45 UTC
When we set the `iso_url` property, the `proxmox-iso` builder always uploads the iso to the specified `iso_storage_pool` storage.

But this wastes time and wears out the storage.

This builder should only upload when the iso file does not exist at the given storage location.

**Comment by stfnx** [comment] 2022-12-17 15:34
I absolutely agree that this should be improved.

Meanwhile, as a workaround you could check the existence of the ISO file via the Proxmox API. See [here](https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/storage/{storage}/content/{volume}).

This may or may not be useful, depending on how you run Packer. Personally I run it from an Ansible playbook, so I just created a task before running Packer, which checks if the ISO is already present on the host. Depending on the result I am either using `iso-file` when its present or `iso-url` and `iso-checksum` when it needs to get downloaded.

Example:
```
pvesh get /nodes/proxmox/storage/local-iso/content | grep 'debian-11.5.0-amd64-netinst.iso'
```

**Comment by stfnx** [comment] 2022-12-17 15:43
This is probably a duplicate of this issue: https://github.com/hashicorp/packer-plugin-proxmox/issues/49

**Comment by modem7** [comment] 2022-12-17 16:39
> I absolutely agree that this should be improved.
> 
> Meanwhile, as a workaround you could check the existence of the ISO file via the Proxmox API. See [here](https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/storage/{storage}/content/{volume}).
> 


It's unfortunate that Packer doesn't have a preprocessor

**Comment by sebastian-de** [comment] 2023-01-11 08:22
After having a look at this [upstream bug report](https://bugzilla.proxmox.com/show_bug.cgi?id=3505), I guess this should be possible.
Two steps are required:
- add support for [download-url](https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/storage/{storage}/download-url) to [proxmox-api-go](https://github.com/Telmate/proxmox-api-go)
- rewrite [step_upload_iso.go](https://github.com/hashicorp/packer-plugin-proxmox/blob/main/builder/proxmox/iso/step_upload_iso.go) to use download-url

The PVE would then skip the download if the file with the correct checksum is already present. If I find the time, I'll have a look at this.

**Comment by sebastian-de** [comment] 2023-01-11 20:00
The change for proxmox-api-go got merged already, so I created a draft here: https://github.com/sebastian-de/packer-plugin-proxmox/commit/9761f385397dd974980d304643d2780eb2d695ab
It works and has the added benefit that ISOs get downloaded to the PVE node directly. Currently they get downloaded to the host packer is running on and then uploaded to the node from there.

I have to add test and clean it up a little.

Since https://github.com/hashicorp/packer-plugin-proxmox/pull/130 is on the finish line (hopefully!), I want to merge my Cloud-Init changes first. After that I'll finish the work here.

**Closed** 2023-02-10 18:05 UTC
Labels: enhancement
