### ISSUE TITLE
"Error creating VM : 506 upload" when trying to upload additional_iso_file

### ISSUE THREAD

**Issue by k2r79** [hashicorp/packer-plugin-proxmox#150] opened 2023-01-29 23:04 UTC
#### Overview of the Issue

When I try to upload `cd_files` through an `additional_iso_file` I get a 506 error :

```
k3s.proxmox-iso.k3s-ubuntu-template: Error creating VM: error creating VM: 506 upload 'Content-Type 'multipart/form-data; boundary=6bab62e418490cdc90766298357c58c377a5bde15f9bae68c8b32280e241' not implemented, error status:  (params: map[agent:1 args: boot: cores:2 cpu:kvm64 description:Packer ephemeral build VM hotplug: ide2:local:iso/ubuntu-22.04.1-live-server-amd64.iso,media=cdrom kvm:true machine: memory:4096 name:k3s net0:virtio=5A:21:7C:11:2C:DF,bridge=vmbr0,firewall=false onboot:false ostype:l26 scsi0:local-lvm:32,format=raw,iothread=false scsihw:lsi sockets:1 startup: tags: vmid:102])
```

I did a quick search and found [some code that seems to come from Proxmox](https://git.proxmox.com/?p=pve-http-server.git;a=blob;f=PVE/APIServer/AnyEvent.pm;h=c55da7f7b4eb60859c6966dbdeb6d9211eed2bfd;hb=refs/heads/master#l1376) but I'm not sure.

This could be a content-type issue as `multipart/form-data` is being sent instead of `application/x-www-form-urlencoded` but it could also be another issue.

#### Reproduction Steps

I reproduce this issue with different types of uploads (ISO, additional ISO files, etc.).

### Plugin and Packer version

- Packer v1.8.5
- github.com/hashicorp/proxmox v1.1.1
- Proxmox VE v7.3-3

### Simplified Packer Buildfile

https://gist.github.com/k2r79/19178199099fb62ca172d905a808f1c9#file-ubuntu-pkr-hcl

### Log Fragments and crash.log files

https://gist.github.com/k2r79/19178199099fb62ca172d905a808f1c9#file-packer-debug-log

**Comment by indrat** [comment] 2023-01-30 04:42
Reverting to github.com/hashicorp/proxmox v1.1.0 successfully uploads `additional_iso_files`.

Working:
- Packer 1.8.4
- github.com/hashicorp/proxmox v1.1.0
- Proxmox VE v7.3-3

Failing:
- Packer 1.8.4
- github.com/hashicorp/proxmox v1.1.1
- Proxmox VE v7.3-3

**Comment by k2r79** [comment] 2023-01-30 08:07
Thanks @indrat 😊

Just tried it and it works perfectly with `github.com/hashicorp/proxmox:1.1.0` 👍

**Comment by sebastian-de** [comment] 2023-01-30 17:16
Hey @k2r79 this is a duplicate of #146

**Closed** 2023-02-01 14:47 UTC
Labels: bug
